"""Export per-flow Kiln/LLM usage evidence for the GWDC submission README.

The submission requires proof of API usage per flow (Kiln call logs plus
on-chain tx hashes). This tool renders a markdown evidence table straight
from the workspace journals so the team only copies it into the README:

    python scripts/export_kiln_usage.py --workspace .validation/ui-workspace

- ``journals/llm.jsonl``   → one row per (flow task × model): call count,
  prompt/response sizes, tokens, est. cost
- ``journals/trading.jsonl`` / ``journals/security_events.jsonl`` → any
  recorded ``tx_hash`` values, so each demo flow can list its anchoring tx

The output is stdout markdown — paste it under “Proof of API usage” in the
README and add the flow descriptions next to each row.
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path


def _read_jsonl(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    rows: list[dict] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(row, dict):
            rows.append(row)
    return rows


def _llm_table(rows: list[dict]) -> str:
    groups: dict[tuple, dict] = defaultdict(lambda: {"calls": 0, "tok": 0, "usd": 0.0, "plen": 0, "rlen": 0})
    for row in rows:
        key = (str(row.get("task") or "?"), str(row.get("model") or row.get("provider") or "?"))
        bucket = groups[key]
        bucket["calls"] += 1
        tokens = row.get("tokens")
        bucket["tok"] += int(tokens) if isinstance(tokens, (int, float)) else 0
        usd = row.get("usd")
        bucket["usd"] += float(usd) if isinstance(usd, (int, float)) else 0.0
        bucket["plen"] += int(row.get("prompt_len") or 0)
        bucket["rlen"] += int(row.get("response_len") or 0)
    lines = [
        "| Flow (task) | Model | Calls | Tokens | Prompt chars | Response chars | Est. cost (USD) |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for (task, model), bucket in sorted(groups.items()):
        lines.append(
            f"| {task} | {model} | {bucket['calls']} | {bucket['tok']} "
            f"| {bucket['plen']} | {bucket['rlen']} | {bucket['usd']:.4f} |"
        )
    if len(groups) == 0:
        lines.append("| (no LLM calls recorded yet) | — | 0 | 0 | 0 | 0 | 0 |")
    return "\n".join(lines)


def _tx_rows(journals: list[tuple[str, list[dict]]]) -> list[str]:
    hashes: list[str] = []
    seen: set[str] = set()

    def walk(value) -> None:
        if isinstance(value, dict):
            for key, item in value.items():
                if key in {"tx_hash", "txhash", "transaction_hash"} and isinstance(item, str) and item:
                    if item not in seen:
                        seen.add(item)
                        hashes.append(item)
                else:
                    walk(item)
        elif isinstance(value, list):
            for item in value:
                walk(item)

    for name, rows in journals:
        for row in rows:
            before = len(hashes)
            walk(row)
            for tx in hashes[before:]:
                hashes[before:before] = []
                hashes.append(f"{tx} (`{name}`)")
    lines = [f"- `{h.split(' (`')[0]}` — journal {h.split(' (`')[1].rstrip(')')}" if " (`" in h else f"- `{h}`" for h in hashes]
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", required=True, help="Nerya workspace root (contains journals/)")
    args = parser.parse_args()
    root = Path(args.workspace)
    journals = root / "journals"

    llm = _read_jsonl(journals / "llm.jsonl")
    print("### Proof of API usage (Kiln / LLM)\n")
    print(_llm_table(llm))
    print()

    trading = _read_jsonl(journals / "trading.jsonl")
    security = _read_jsonl(journals / "security_events.jsonl")
    tx_lines = _tx_rows([("trading.jsonl", trading), ("security_events.jsonl", security)])
    print("### On-chain anchoring (tx hashes)\n")
    if tx_lines:
        print("\n".join(tx_lines))
    else:
        print("- (no on-chain transactions recorded yet — run the mandate anchoring flow first)")
    print()
    print(f"_Source: `{journals}` — regenerated by `python scripts/export_kiln_usage.py --workspace <root>`_")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
